Sumbitted by 2462332_Paridhi_Adhikari

4.1 Warming Up Exercise: Basic Vector and Matrix Operation with Numpy.

Problem - 1: Array Creation:

In [5]:
import numpy as np
arr = np.empty((2,2))
print(arr)


[[2.78943629e-315 0.00000000e+000]
 [6.57606496e-310 2.42092166e-322]]


In [6]:
arr = np.ones((4,2))
print(arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [7]:
arr = np.full((4,2), 13)
print(arr)

[[13 13]
 [13 13]
 [13 13]
 [13 13]]


In [8]:
arr = [[1,2], [3,4]]
arr2 = np.zeros_like(arr)
print(arr2)

[[0 0]
 [0 0]]


In [9]:
arr = [[1,2], [3,4]]
arr2 = np.ones_like(arr)
print(arr2)

[[1 1]
 [1 1]]


In [10]:
new_list = [1,2,3,4]
arr = np.array(new_list)
print(arr)

[1 2 3 4]


Prolem - 2: Array Manipulation: Numerical Ranges and Array indexing:

In [11]:
arr = np.arange(10, 50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [12]:
arr=np.arange(0,9)
reshape_arr=arr.reshape(3,3)
print(reshape_arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [13]:
arr= np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
import random as random
arr = np.random.random(30)
print(arr)
mean= np.mean(arr)
print(f"mean is {mean}")

[0.87813301 0.41752267 0.18352273 0.5468554  0.03847065 0.87888345
 0.54858085 0.54945352 0.86971415 0.06444735 0.20806153 0.21545673
 0.79666149 0.11273939 0.38525389 0.34536929 0.8957376  0.27417188
 0.89796267 0.30822968 0.73887147 0.14235502 0.58523597 0.40624821
 0.67174755 0.87509426 0.96548247 0.62808159 0.15290127 0.66828965]
mean is 0.5083178454891649


In [15]:
arr= np.random.random((10,10))
max= np.max(arr)
min=np.min(arr)
print(f"max is {max} and min is {min}")

max is 0.9923751511004142 and min is 0.003343257110009934


In [16]:
arr=np.zeros(10)
print(arr)
arr[4]=1
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [17]:
arr=[1, 2, 0, 0, 4, 0]
reverse = np.flip(arr)
print(reverse)

[0 4 0 0 2 1]


In [18]:
n,m = 5, 5
arr = np.zeros((n,m))
arr[0, :] = 1
arr[-1, :] = 1
arr[:, 0] = 1
arr[:, -1] = 1
print(arr)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [19]:
checkboard=np.ones((8,8))
checkboard[1::2, ::2]=0
checkboard[::2, 1::2]=0
print(checkboard)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


In [20]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
print(np.add(x,y))
print(np.add(v,w))
print(np.subtract(x,y))
print(np.subtract(v,w))
print((x,y)*2)
print((v,w)*5)
print(np.square(x))
print(np.square(y))
print(np.square(v))
print(np.square(w))
print(np.dot(v,w))
print(np.dot(x,v))
print(np.dot(x,y))
print(np.concatenate((x,y), axis=0))#row concatenation
#v anw w reshape
v=v.reshape(2,1)
w=w.reshape(2,1)
print(np.concatenate((v,w), axis=1))#column concatenation
print(np.concatenate((x,v), axis =1))
#print(np.concatenate((x,v), axis=0))# same as above different dimension

[[ 6  8]
 [10 13]]
[20 22]
[[-4 -4]
 [-4 -3]]
[-2 -2]
(array([[1, 2],
       [3, 5]]), array([[5, 6],
       [7, 8]]), array([[1, 2],
       [3, 5]]), array([[5, 6],
       [7, 8]]))
(array([ 9, 10]), array([11, 12]), array([ 9, 10]), array([11, 12]), array([ 9, 10]), array([11, 12]), array([ 9, 10]), array([11, 12]), array([ 9, 10]), array([11, 12]))
[[ 1  4]
 [ 9 25]]
[[25 36]
 [49 64]]
[ 81 100]
[121 144]
219
[29 77]
[[19 22]
 [50 58]]
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[[ 9 11]
 [10 12]]
[[ 1  2  9]
 [ 3  5 10]]


In [21]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
A_inverse=np.linalg.inv(A)
print(np.dot(A, A_inverse))
print(np.dot(A,B))
print(np.dot(B,A))
AB = np.dot(A,B)
at= np.transpose(A)
bt= np.transpose(B)
print(np.dot(at,bt))




[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
[[23 13]
 [51 29]]
[[36 44]
 [13 16]]
[[36 13]
 [44 16]]


In [22]:
A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B = np.array([-1, -3, 9])
A_inverse = np.linalg.inv(A)
X = np.dot(A_inverse, B)
print(X)

[ 2.  1. -2.]


Matrix Multiplication Test (1000x1000)

In [23]:
import timeit
list1 = list(range(1000000))
list2 = list(range(1000000))


In [24]:
from timeit import timeit
def add_python(Z1, Z2):
  return [z1 + z2 for z1, z2 in zip(Z1, Z2)]
def add_numpy(Z1, Z2):
  return np.add(Z1, Z2)
Z1 = random.sample(range(1000000), 10000)
Z2 = random.sample(range(1000000), 10000)
python_time = timeit("add_python(Z1,Z2)", globals=globals(), number=100)
numpy_time = timeit("add_numpy(Z1,Z2)", globals=globals(), number=100)
print(f"Pure Python addition: {python_time:.2f} s per loop")
print(f"Numpy addition: {numpy_time:.2f} s per loop")

Pure Python addition: 0.06 s per loop
Numpy addition: 0.12 s per loop


In [25]:
from timeit import timeit
def mul_python(Z1, Z2):
  return [z1 * z2 for z1, z2 in zip(Z1, Z2)]
def mul_numpy(Z1, Z2):
  return np.multiply(Z1, Z2)
Z1 = random.sample(range(1000000), 10000)
Z2 = random.sample(range(1000000), 10000)
python_time = timeit("mul_python(Z1,Z2)", globals=globals(), number=100)
numpy_time = timeit("mul_numpy(Z1,Z2)", globals=globals(), number=100)
print(f"Pure Python multiplication: {python_time:.2f} s per loop")
print(f"Numpy multiplication: {numpy_time:.2f} s per loop")

Pure Python multiplication: 0.08 s per loop
Numpy multiplication: 0.13 s per loop


In [26]:
from timeit import timeit
def dot_python(Z1, Z2):
  return sum(z1 * z2 for z1, z2 in zip(Z1, Z2))
def dot_numpy(Z1, Z2):
  return np.dot(Z1, Z2)
Z1 = random.sample(range(1000000), 10000)
Z2 = random.sample(range(1000000), 10000)
python_time = timeit("dot_python(Z1,Z2)", globals=globals(), number=100)
numpy_time = timeit("dot_numpy(Z1,Z2)", globals=globals(), number=100)
print(f"Pure Python dot product: {python_time:.2f} s per loop")
print(f"Numpy dot product: {numpy_time:.2f} s per loop")

Pure Python dot product: 0.09 s per loop
Numpy dot product: 0.15 s per loop


In [27]:
from timeit import timeit
matrix1 = np.random.random((1000, 1000))
matrix2 = np.random.random((1000, 1000))
list1 = matrix1.tolist()
list2 = matrix2.tolist()
def matrix_python(list1, list2):
  list2_T = list(zip(*list2))
  return [[sum(a*b for a,b in zip(list1_row,list2_col)) for list2_col in list2_T] for list1_row in list1]
def matrix_numpy(matrix1, matrix2):
  return np.matmul(matrix1, matrix2)
#Z1 = random.sample(range(1000000), 10000)
#Z2 = random.sample(range(1000000), 10000)
python_time = timeit("matrix_python(list1,list2)", globals=globals(), number=1)
numpy_time = timeit("matrix_numpy(matrix1,matrix2)", globals=globals(), number=1)
print(f"Pure Python matrix multiplication: {python_time:.2f} s per loop")
print(f"Numpy matrix multiplication: {numpy_time:.2f} s per loop")

Pure Python matrix multiplication: 128.13 s per loop
Numpy matrix multiplication: 0.07 s per loop
